// <auto-generated />
using Freecrmlance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace Freecrmlance.Infrastructure.Persistence.Migrations;
[DbContext(typeof(FreecrmlanceDbContext))]
[Migration("20261002090000_AddAuditTemplates")]
partial class AddAuditTemplates { }
