// <auto-generated />
using Freecrmlance.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace Freecrmlance.Infrastructure.Persistence.Migrations;
[DbContext(typeof(FreecrmlanceDbContext))][Migration("20261004103000_AddAuditReportTransmissions")]partial class AddAuditReportTransmissions{}
