// <auto-generated />
using System;
using Freecrmlance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freecrmlance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreecrmlanceDbContext))]
    partial class FreecrmlanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);


            modelBuilder.Entity("Freecrmlance.Domain.Audits.Audit", b =>
                { b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid"); b.Property<DateTime?>("CompletedAtUtc").HasColumnType("timestamp with time zone"); b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone"); b.Property<Guid>("CustomerId").HasColumnType("uuid"); b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)"); b.Property<string>("Reference").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)"); b.Property<DateTime?>("StartedAtUtc").HasColumnType("timestamp with time zone"); b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)"); b.Property<Guid>("TemplateId").HasColumnType("uuid"); b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)"); b.Property<Guid>("WorkspaceId").HasColumnType("uuid"); b.HasKey("Id"); b.HasIndex("WorkspaceId","CustomerId"); b.HasIndex("WorkspaceId","Reference").IsUnique(); b.ToTable("Audits","audit"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditReportVersion", b =>
                { b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid"); b.Property<Guid>("AuditId").HasColumnType("uuid"); b.Property<DateTime>("FinalizedAtUtc").HasColumnType("timestamp with time zone"); b.Property<string>("FinalizedByUserId").IsRequired().HasMaxLength(450).HasColumnType("character varying(450)"); b.Property<Guid?>("GeneratedDocumentId").HasColumnType("uuid"); b.Property<string>("Hash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)"); b.Property<string>("Snapshot").IsRequired().HasColumnType("text"); b.Property<int>("VersionNumber").HasColumnType("integer"); b.HasKey("Id"); b.HasIndex("GeneratedDocumentId"); b.HasIndex("AuditId","VersionNumber").IsUnique(); b.ToTable("AuditReportVersions","audit"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditSection", b =>
                { b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid"); b.Property<Guid>("AuditId").HasColumnType("uuid"); b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)"); b.Property<int>("Position").HasColumnType("integer"); b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)"); b.HasKey("Id"); b.HasIndex("AuditId","Position").IsUnique(); b.ToTable("AuditSections","audit"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditItem", b =>
                { b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid"); b.Property<Guid>("AuditSectionId").HasColumnType("uuid"); b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)"); b.Property<bool>("IsRequired").HasColumnType("boolean"); b.Property<string>("Label").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)"); b.Property<string>("Options").HasMaxLength(4000).HasColumnType("character varying(4000)"); b.Property<int>("Position").HasColumnType("integer"); b.Property<string>("ResponseType").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)"); b.HasKey("Id"); b.HasIndex("AuditSectionId","Position").IsUnique(); b.ToTable("AuditItems","audit"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditEvidence", b =>
                { b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid"); b.Property<Guid>("AuditItemId").HasColumnType("uuid"); b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone"); b.Property<Guid>("DocumentId").HasColumnType("uuid"); b.Property<string>("UploadedByUserId").IsRequired().HasMaxLength(450).HasColumnType("character varying(450)"); b.HasKey("Id"); b.HasIndex("AuditItemId"); b.HasIndex("DocumentId").IsUnique(); b.ToTable("AuditEvidence","audit"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditItemResponse", b =>
                { b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid"); b.Property<Guid>("AuditItemId").HasColumnType("uuid"); b.Property<string>("Observation").HasMaxLength(4000).HasColumnType("character varying(4000)"); b.Property<string>("Recommendation").HasMaxLength(4000).HasColumnType("character varying(4000)"); b.Property<DateTime>("UpdatedAtUtc").HasColumnType("timestamp with time zone"); b.Property<string>("UpdatedByUserId").IsRequired().HasMaxLength(450).HasColumnType("character varying(450)"); b.Property<string>("Value").HasMaxLength(4000).HasColumnType("character varying(4000)"); b.HasKey("Id"); b.HasIndex("AuditItemId").IsUnique(); b.ToTable("AuditItemResponses","audit"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditNumberSequence", b =>
                { b.Property<Guid>("WorkspaceId").HasColumnType("uuid"); b.Property<int>("Year").HasColumnType("integer"); b.Property<int>("LastNumber").HasColumnType("integer"); b.HasKey("WorkspaceId","Year"); b.ToTable("AuditNumberSequences","audit"); });

            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditTemplate", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<bool>("IsArchived").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("WorkspaceId").HasColumnType("uuid");
                    b.HasKey("Id"); b.HasIndex("WorkspaceId", "IsArchived"); b.ToTable("AuditTemplates", "audit");
                });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditReportVersion", b =>
                { b.HasOne("Freecrmlance.Domain.Audits.Audit", null).WithMany().HasForeignKey("AuditId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.HasOne("Freecrmlance.Domain.Crm.Document", null).WithMany().HasForeignKey("GeneratedDocumentId").OnDelete(DeleteBehavior.SetNull); });

            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditSection", b =>
                { b.HasOne("Freecrmlance.Domain.Audits.Audit", null).WithMany("Sections").HasForeignKey("AuditId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditItem", b =>
                { b.HasOne("Freecrmlance.Domain.Audits.AuditSection", null).WithMany("Items").HasForeignKey("AuditSectionId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });

            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditEvidence", b =>
                { b.HasOne("Freecrmlance.Domain.Audits.AuditItem", null).WithMany().HasForeignKey("AuditItemId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.HasOne("Freecrmlance.Domain.Crm.Document", null).WithMany().HasForeignKey("DocumentId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });

            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditItemResponse", b =>
                { b.HasOne("Freecrmlance.Domain.Audits.AuditItem", null).WithOne().HasForeignKey("Freecrmlance.Domain.Audits.AuditItemResponse","AuditItemId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });

            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditTemplateSection", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("AuditTemplateId").HasColumnType("uuid");
                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<int>("Position").HasColumnType("integer");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.HasKey("Id"); b.HasIndex("AuditTemplateId", "Position").IsUnique(); b.ToTable("AuditTemplateSections", "audit");
                });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditTemplateItem", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<bool>("IsRequired").HasColumnType("boolean");
                    b.Property<string>("Label").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("Options").HasMaxLength(4000).HasColumnType("character varying(4000)");
                    b.Property<int>("Position").HasColumnType("integer");
                    b.Property<string>("ResponseType").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<Guid>("SectionId").HasColumnType("uuid");
                    b.HasKey("Id"); b.HasIndex("SectionId", "Position").IsUnique(); b.ToTable("AuditTemplateItems", "audit");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Billing.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerLegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerSiren")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("CustomerSiret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("CustomerVatNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DraftReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EarlyPaymentDiscountTerms")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatePaymentPenaltyTerms")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PurchaseOrderReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("RecoveryCostIndemnity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SellerAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SellerAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SellerCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SellerContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("SellerContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SellerCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("SellerLegalForm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SellerLegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SellerPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SellerSiren")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("SellerSiret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("SellerVatNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("ServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceQuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatExemptionMention")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceQuoteId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "CustomerId");

                    b.HasIndex("WorkspaceId", "Number")
                        .IsUnique()
                        .HasFilter("\"Number\" IS NOT NULL");

                    b.ToTable("Invoices", "billing");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Billing.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines", "billing");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Billing.InvoiceNumberSequence", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer");

                    b.HasKey("WorkspaceId", "Year");

                    b.ToTable("InvoiceNumberSequences", "billing");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WorkspaceId", "CustomerId");

                    b.ToTable("Contacts", "crm");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BillingAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BillingAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BillingCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("BillingPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Siren")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Customers", "crm");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "CustomerId");

                    b.ToTable("Documents", "crm");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.DocumentShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "CustomerId", "DocumentId");

                    b.ToTable("DocumentShares", "crm");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "CustomerId");

                    b.HasIndex("WorkspaceId", "Number")
                        .IsUnique();

                    b.ToTable("Quotes", "crm");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.QuoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteLines", "crm");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.QuoteShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "CustomerId", "QuoteId");

                    b.ToTable("QuoteShares", "crm");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Platform.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("LegalForm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Siren")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", "platform");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Platform.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("WorkspaceId", "UserId");

                    b.ToTable("WorkspaceMembers", "platform");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });


            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditTemplateSection", b =>
                { b.HasOne("Freecrmlance.Domain.Audits.AuditTemplate", null).WithMany("Sections").HasForeignKey("AuditTemplateId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditTemplateItem", b =>
                { b.HasOne("Freecrmlance.Domain.Audits.AuditTemplateSection", null).WithMany("Items").HasForeignKey("SectionId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });

            modelBuilder.Entity("Freecrmlance.Domain.Billing.InvoiceLine", b =>
                {
                    b.HasOne("Freecrmlance.Domain.Billing.Invoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.Contact", b =>
                {
                    b.HasOne("Freecrmlance.Domain.Crm.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.Document", b =>
                {
                    b.HasOne("Freecrmlance.Domain.Crm.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.DocumentShare", b =>
                {
                    b.HasOne("Freecrmlance.Domain.Crm.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.QuoteLine", b =>
                {
                    b.HasOne("Freecrmlance.Domain.Crm.Quote", null)
                        .WithMany("Lines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.QuoteShare", b =>
                {
                    b.HasOne("Freecrmlance.Domain.Crm.Quote", null)
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Freecrmlance.Domain.Platform.WorkspaceMember", b =>
                {
                    b.HasOne("Freecrmlance.Domain.Platform.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });


            modelBuilder.Entity("Freecrmlance.Domain.Audits.Audit", b => { b.Navigation("Sections"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditSection", b => { b.Navigation("Items"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditTemplate", b => { b.Navigation("Sections"); });
            modelBuilder.Entity("Freecrmlance.Domain.Audits.AuditTemplateSection", b => { b.Navigation("Items"); });

            modelBuilder.Entity("Freecrmlance.Domain.Billing.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Freecrmlance.Domain.Crm.Quote", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
