using Freecrmlance.Application.Audits;using Freecrmlance.Application.Crm;using Freecrmlance.Application.Platform;using Freecrmlance.Domain.Audits;using Freecrmlance.Domain.Crm;using Freecrmlance.Infrastructure.Audits;using Freecrmlance.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;using NUnit.Framework;using Testcontainers.PostgreSql;
namespace Freecrmlance.IntegrationTests.Audits;
public sealed class AuditReportTests
{
 [Test]public async Task Generate_persists_document_and_downloads_it_for_version_snapshot()
 {
  await using var pg=new PostgreSqlBuilder().WithImage("postgres:17-alpine").Build();await pg.StartAsync();var o=new DbContextOptionsBuilder<FreecrmlanceDbContext>().UseNpgsql(pg.GetConnectionString()).Options;var wid=Guid.NewGuid();await using var db=new FreecrmlanceDbContext(o);await db.Database.MigrateAsync();var customer=new Customer(wid,"Client");db.Customers.Add(customer);var audit=new Audit(wid,customer.Id,Guid.NewGuid(),"AUD-1","Audit figé",null);db.Audits.Add(audit);await db.SaveChangesAsync();var snapshot="""{"schemaVersion":1,"audit":{"id":"00000000-0000-0000-0000-000000000001","workspaceId":"00000000-0000-0000-0000-000000000002","customerId":"00000000-0000-0000-0000-000000000003","templateId":"00000000-0000-0000-0000-000000000004","reference":"AUD-1","title":"Titre snapshot","description":null,"createdAtUtc":"2026-10-04T00:00:00Z"},"sections":[]}""";var v=new AuditReportVersion(audit.Id,1,DateTime.UtcNow,"user",snapshot,new string('a',64));db.AuditReportVersions.Add(v);await db.SaveChangesAsync();var storage=new MemoryStorage();var generator=new StubPdf();var service=new AuditReportService(db,new StubWorkspace(wid),storage,generator);
  var result=await service.GenerateAsync(audit.Id,v.Id);Assert.That(result.Succeeded,Is.True);Assert.That(generator.Last!.Title,Is.EqualTo("Titre snapshot"));Assert.That(generator.Last.Reference,Is.EqualTo("AUD-1"));var persisted=await db.AuditReportVersions.AsNoTracking().SingleAsync(x=>x.Id==v.Id);Assert.That(persisted.GeneratedDocumentId,Is.EqualTo(result.DocumentId));var download=await service.DownloadAsync(audit.Id,v.Id);Assert.That(download,Is.Not.Null);using var ms=new MemoryStream();await download!.Content.CopyToAsync(ms);Assert.That(ms.ToArray(),Is.EqualTo(new byte[]{37,80,68,70}));
 }
 [Test]public async Task Foreign_workspace_cannot_generate_report()
 {
  await using var pg=new PostgreSqlBuilder().WithImage("postgres:17-alpine").Build();await pg.StartAsync();var o=new DbContextOptionsBuilder<FreecrmlanceDbContext>().UseNpgsql(pg.GetConnectionString()).Options;var owner=Guid.NewGuid();await using var db=new FreecrmlanceDbContext(o);await db.Database.MigrateAsync();var customer=new Customer(owner,"Client");db.Customers.Add(customer);var audit=new Audit(owner,customer.Id,Guid.NewGuid(),"AUD-2","Audit",null);db.Audits.Add(audit);await db.SaveChangesAsync();var v=new AuditReportVersion(audit.Id,1,DateTime.UtcNow,"user","{}",new string('b',64));db.AuditReportVersions.Add(v);await db.SaveChangesAsync();var service=new AuditReportService(db,new StubWorkspace(Guid.NewGuid()),new MemoryStorage(),new StubPdf());var result=await service.GenerateAsync(audit.Id,v.Id);Assert.That(result.Succeeded,Is.False);Assert.That(result.Error,Is.EqualTo("Version d'audit introuvable."));
 }
 private sealed class StubPdf:IAuditReportPdfGenerator{public AuditReportPdfModel? Last{get;private set;}public byte[] Generate(AuditReportPdfModel m){Last=m;return new byte[]{37,80,68,70};}}
 private sealed class MemoryStorage:IFileStorage{private readonly Dictionary<string,byte[]> files=[];public async Task<string> SaveAsync(Stream c,CancellationToken ct=default){using var m=new MemoryStream();await c.CopyToAsync(m,ct);var k=Guid.NewGuid().ToString("N");files[k]=m.ToArray();return k;}public Task<Stream> OpenReadAsync(string k,CancellationToken ct=default)=>Task.FromResult<Stream>(new MemoryStream(files[k],false));public Task DeleteAsync(string k,CancellationToken ct=default){files.Remove(k);return Task.CompletedTask;}}
 private sealed class StubWorkspace(Guid id):IWorkspaceContext{public Task<Guid?> GetCurrentWorkspaceIdAsync(CancellationToken ct=default)=>Task.FromResult<Guid?>(id);public Task<Guid> RequireCurrentWorkspaceIdAsync(CancellationToken ct=default)=>Task.FromResult(id);}
}
