using Freecrmlance.Application.Crm;using Freecrmlance.Application.Platform;using Freecrmlance.Domain.Audits;using Freecrmlance.Domain.Crm;using Freecrmlance.Infrastructure.Audits;using Freecrmlance.Infrastructure.Crm;using Freecrmlance.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;using NUnit.Framework;using Testcontainers.PostgreSql;
namespace Freecrmlance.IntegrationTests.Audits;
public sealed class AuditTransmissionTests
{
 [Test]public async Task Generated_version_can_be_transmitted_and_traced()
 {
  await using var pg=new PostgreSqlBuilder().WithImage("postgres:17-alpine").Build();await pg.StartAsync();var o=new DbContextOptionsBuilder<FreecrmlanceDbContext>().UseNpgsql(pg.GetConnectionString()).Options;var wid=Guid.NewGuid();await using var db=new FreecrmlanceDbContext(o);await db.Database.MigrateAsync();var customer=new Customer(wid,"Client");db.Customers.Add(customer);var audit=new Audit(wid,customer.Id,Guid.NewGuid(),"AUD-1","Audit",null);db.Audits.Add(audit);var document=new Document(wid,customer.Id,"audit.pdf","application/pdf",4,"file1");db.Documents.Add(document);await db.SaveChangesAsync();var version=new AuditReportVersion(audit.Id,1,DateTime.UtcNow,"user","{}",new string('a',64));version.SetGeneratedDocument(document.Id);db.AuditReportVersions.Add(version);await db.SaveChangesAsync();var files=new MemoryStorage();files.Files["file1"]=[37,80,68,70];var shares=new DocumentShareService(db,new StubWorkspace(wid),files);var service=new AuditTransmissionService(db,new StubWorkspace(wid),shares);
  var result=await service.CreateAsync(audit.Id,version.Id,"client@example.test","user-1");Assert.That(result.Succeeded,Is.True);Assert.That(result.Token,Is.Not.Empty);var sent=await service.ListAsync(audit.Id);Assert.That(sent,Has.Count.EqualTo(1));Assert.Multiple(()=>{Assert.That(sent![0].VersionNumber,Is.EqualTo(1));Assert.That(sent[0].Recipient,Is.EqualTo("client@example.test"));Assert.That(sent[0].SentByUserId,Is.EqualTo("user-1"));});var download=await shares.DownloadAsync(result.Token!);Assert.That(download,Is.Not.Null);
 }

 [Test]public async Task Same_generated_version_can_be_transmitted_to_multiple_recipients_with_independent_tokens()
 {
  await using var pg=new PostgreSqlBuilder().WithImage("postgres:17-alpine").Build();await pg.StartAsync();var o=new DbContextOptionsBuilder<FreecrmlanceDbContext>().UseNpgsql(pg.GetConnectionString()).Options;var wid=Guid.NewGuid();await using var db=new FreecrmlanceDbContext(o);await db.Database.MigrateAsync();var customer=new Customer(wid,"Client");db.Customers.Add(customer);var audit=new Audit(wid,customer.Id,Guid.NewGuid(),"AUD-MULTI","Audit",null);db.Audits.Add(audit);var document=new Document(wid,customer.Id,"audit.pdf","application/pdf",4,"file1");db.Documents.Add(document);await db.SaveChangesAsync();var version=new AuditReportVersion(audit.Id,1,DateTime.UtcNow,"user","{}",new string('c',64));version.SetGeneratedDocument(document.Id);db.AuditReportVersions.Add(version);await db.SaveChangesAsync();var files=new MemoryStorage();files.Files["file1"]=[37,80,68,70];var shares=new DocumentShareService(db,new StubWorkspace(wid),files);var service=new AuditTransmissionService(db,new StubWorkspace(wid),shares);
  var first=await service.CreateAsync(audit.Id,version.Id,"one@example.test","user");var second=await service.CreateAsync(audit.Id,version.Id,"two@example.test","user");
  Assert.Multiple(()=>{Assert.That(first.Succeeded,Is.True);Assert.That(second.Succeeded,Is.True);Assert.That(second.Token,Is.Not.EqualTo(first.Token));});
  Assert.That(await db.AuditReportTransmissions.CountAsync(),Is.EqualTo(2));Assert.That(await db.DocumentShares.CountAsync(),Is.EqualTo(2));
 }
 [Test]public async Task Version_without_pdf_cannot_be_transmitted()
 {
  await using var pg=new PostgreSqlBuilder().WithImage("postgres:17-alpine").Build();await pg.StartAsync();var o=new DbContextOptionsBuilder<FreecrmlanceDbContext>().UseNpgsql(pg.GetConnectionString()).Options;var wid=Guid.NewGuid();await using var db=new FreecrmlanceDbContext(o);await db.Database.MigrateAsync();var customer=new Customer(wid,"Client");db.Customers.Add(customer);var audit=new Audit(wid,customer.Id,Guid.NewGuid(),"AUD-2","Audit",null);db.Audits.Add(audit);await db.SaveChangesAsync();var version=new AuditReportVersion(audit.Id,1,DateTime.UtcNow,"user","{}",new string('b',64));db.AuditReportVersions.Add(version);await db.SaveChangesAsync();var files=new MemoryStorage();var service=new AuditTransmissionService(db,new StubWorkspace(wid),new DocumentShareService(db,new StubWorkspace(wid),files));var result=await service.CreateAsync(audit.Id,version.Id,"client","user");Assert.That(result.Succeeded,Is.False);Assert.That(result.Error,Does.Contain("PDF"));
 }
 private sealed class MemoryStorage:IFileStorage{public Dictionary<string,byte[]> Files{get;}=[];public async Task<string> SaveAsync(Stream s,CancellationToken ct=default){using var m=new MemoryStream();await s.CopyToAsync(m,ct);var k=Guid.NewGuid().ToString("N");Files[k]=m.ToArray();return k;}public Task<Stream> OpenReadAsync(string k,CancellationToken ct=default)=>Task.FromResult<Stream>(new MemoryStream(Files[k],false));public Task DeleteAsync(string k,CancellationToken ct=default){Files.Remove(k);return Task.CompletedTask;}}
 private sealed class StubWorkspace(Guid id):IWorkspaceContext{public Task<Guid?> GetCurrentWorkspaceIdAsync(CancellationToken ct=default)=>Task.FromResult<Guid?>(id);public Task<Guid> RequireCurrentWorkspaceIdAsync(CancellationToken ct=default)=>Task.FromResult(id);}
}
