using System.Security.Claims;using System.Text.Json;using Freecrmlance.Application.Audits;using Freecrmlance.Application.Crm;using Freecrmlance.Web.Models.Audits;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.Rendering;
namespace Freecrmlance.Web.Controllers;
[Authorize]public sealed class AuditsController(IAuditService audits,IAuditFinalizationService finalization,IAuditReportService reports,IAuditTransmissionService transmissions,IAuditHistoryService history,IAuditEvidenceService evidence,IAuditTemplateService templates,ICustomerService customers):Controller
{
 [HttpGet]public async Task<IActionResult> Index(CancellationToken ct)=>View(await audits.ListAsync(ct));
 [HttpGet]public async Task<IActionResult> Create(CancellationToken ct){var model=new CreateAuditViewModel();await Populate(model,ct);return View(model);}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> Create(CreateAuditViewModel model,CancellationToken ct){if(!ModelState.IsValid){await Populate(model,ct);return View(model);}var id=await audits.CreateAsync(new CreateAuditCommand(model.CustomerId,model.TemplateId,model.Title,model.Description),ct);if(id is null){ModelState.AddModelError(string.Empty,"Le client ou le modèle d'audit n'est pas disponible.");await Populate(model,ct);return View(model);}return RedirectToAction(nameof(Details),new{id});}
 [HttpGet]public async Task<IActionResult> Details(Guid id,CancellationToken ct){var audit=await audits.GetAsync(id,ct);return audit is null?NotFound():View(audit);}
 [HttpGet]public async Task<IActionResult> Workspace(Guid id,CancellationToken ct){var audit=await audits.GetAsync(id,ct);if(audit is null)return NotFound();var files=await evidence.ListAsync(id,ct);if(files is null)return NotFound();var versions=await finalization.ListVersionsAsync(id,ct);if(versions is null)return NotFound();var sent=await transmissions.ListAsync(id,ct);if(sent is null)return NotFound();var timeline=await history.ListAsync(id,ct);return timeline is null?NotFound():View(new AuditWorkspaceViewModel{Audit=audit,Evidence=files,Versions=versions,Transmissions=sent,History=timeline});}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> SaveResponse(Guid auditId,Guid auditItemId,string? value,string? observation,string? recommendation,string[]? selectedValues,CancellationToken ct)
 {
  if(selectedValues is {Length:>0})value=JsonSerializer.Serialize(selectedValues);
  var userId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(userId))return Challenge();
  var error=await audits.SaveResponseAsync(new SaveAuditResponseCommand(auditId,auditItemId,value,observation,recommendation,userId),ct);
  if(error is not null)TempData["AuditError"]=error;else TempData["AuditSuccess"]="Critère enregistré.";
  return WorkspaceRedirect(auditId,"work");
 }
 [HttpPost,ValidateAntiForgeryToken,RequestSizeLimit(10 * 1024 * 1024)]public async Task<IActionResult> UploadEvidence(Guid auditId,Guid auditItemId,IFormFile file,CancellationToken ct)
 {
  if(file is null||file.Length==0){TempData["AuditError"]="Sélectionnez un fichier.";return RedirectToAction(nameof(Workspace),new{id=auditId});}
  var userId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(userId))return Challenge();
  await using var content=file.OpenReadStream();var error=await evidence.UploadAsync(auditId,auditItemId,file.FileName,file.ContentType,file.Length,content,userId,ct);
  if(error is not null)TempData["AuditError"]=error;else TempData["AuditSuccess"]="Preuve ajoutée.";
  return RedirectToAction(nameof(Workspace),new{id=auditId});
 }
 [HttpGet]public async Task<IActionResult> DownloadEvidence(Guid auditId,Guid evidenceId,CancellationToken ct){var file=await evidence.DownloadAsync(auditId,evidenceId,ct);return file is null?NotFound():File(file.Content,file.ContentType,file.FileName);}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> DeleteEvidence(Guid auditId,Guid evidenceId,CancellationToken ct){var error=await evidence.DeleteAsync(auditId,evidenceId,ct);if(error is not null)TempData["AuditError"]=error;else TempData["AuditSuccess"]="Preuve supprimée.";return RedirectToAction(nameof(Workspace),new{id=auditId});}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> FinalizeAudit(Guid auditId,CancellationToken ct){var userId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(userId))return Challenge();var result=await finalization.FinalizeAsync(auditId,userId,ct);if(!result.Succeeded)TempData["AuditError"]=result.Error;else TempData["AuditSuccess"]="Audit finalisé : une version immuable a été créée.";return RedirectToAction(nameof(Workspace),new{id=auditId});}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> ReopenAudit(Guid auditId,CancellationToken ct){var userId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(userId))return Challenge();var error=await finalization.ReopenAsync(auditId,userId,ct);if(error is not null)TempData["AuditError"]=error;else TempData["AuditSuccess"]="Audit rouvert pour correction.";return RedirectToAction(nameof(Workspace),new{id=auditId});}
 [HttpGet]public async Task<IActionResult> VerifyVersion(Guid auditId,Guid versionId,CancellationToken ct){TempData["AuditSuccess"]=await finalization.VerifyHashAsync(auditId,versionId,ct)?"Empreinte SHA-256 vérifiée.":"Échec de vérification de l'empreinte.";return RedirectToAction(nameof(Workspace),new{id=auditId});}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> GenerateReport(Guid auditId,Guid versionId,CancellationToken ct){var result=await reports.GenerateAsync(auditId,versionId,ct);if(!result.Succeeded)TempData["AuditError"]=result.Error;else TempData["AuditSuccess"]="Rapport PDF généré.";return RedirectToAction(nameof(Workspace),new{id=auditId});}
 [HttpGet]public async Task<IActionResult> DownloadReport(Guid auditId,Guid versionId,CancellationToken ct){var report=await reports.DownloadAsync(auditId,versionId,ct);return report is null?NotFound():File(report.Content,report.ContentType,report.FileName);}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> TransmitReport(Guid auditId,Guid versionId,string recipient,CancellationToken ct){var userId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(userId))return Challenge();var result=await transmissions.CreateAsync(auditId,versionId,recipient,userId,ct);if(!result.Succeeded)TempData["AuditError"]=result.Error;else{TempData["AuditSuccess"]="Lien de transmission créé.";TempData["AuditShareUrl"]=Url.Action("Download","SharedDocuments",new{token=result.Token},Request.Scheme);}return RedirectToAction(nameof(Workspace),new{id=auditId});}
 private IActionResult WorkspaceRedirect(Guid auditId,string tab)=>RedirectToAction(nameof(Workspace),new{id=auditId,tab});
 private async Task Populate(CreateAuditViewModel m,CancellationToken ct){m.Customers=(await customers.ListAsync(ct)).Select(x=>new SelectListItem(x.Name,x.Id.ToString())).ToArray();m.Templates=(await templates.ListAsync(false,ct)).Where(x=>!x.IsArchived).Select(x=>new SelectListItem(x.Name,x.Id.ToString())).ToArray();}
}
